### PR TITLE
Adding game

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
# Adding a Rock-Paper-Scissor Game 

**ScreenShot**
Screenshot 2023-05-26 193636

### CODE REVIEW

**Comment by Aman1-coder** [comment]
@DhairyaMajmudar You game is good, but please set a criteria for winner and create a new folder for images in your folder

**Comment by DhairyaMajmudar** [comment]
@Aman1-coder I have committed the mentioned changes

**Review by Durgesh4993 — APPROVED** [review]
Game and Code is running Properly, @Aman1-coder you can merge it

**Comment by Aman1-coder** [comment]
Ok @Durgesh4993 Thank you for review

**Comment by DhairyaMajmudar** [comment]
Thank you @Durgesh4993 Sir for reviewing and @Aman1-coder for merging my game 😀

**Pull request merged**
