### PR TITLE
Add Code of Conduct

### LINKED ISSUE #34: Add Code of Conduct
I want to create CODE_OF_CONDUCT.md for this repository.

This contribution is part of GSSoC'23.

### PR DESCRIPTION
**Pull request by Sriparno08**
I have created a Code of Conduct for the repository.

Fixes #34

This PR is part of GSSoC'23.

### CODE REVIEW

**Comment by Aman1-coder** [comment]
@Sriparno08 https://docs.google.com/document/d/1HuP7z881u_d9ZOcL-DoiVve1L7Ta1qwL/edit according to this please update the readme file then I'll merge the PR

**Comment by Aman1-coder** [comment]
https://github.com/nawed2611/sample-pa-readme-gssoc23/blob/main/README.md It is reference template

**Comment by Sriparno08** [comment]
Hey @Aman1-coder, this issue already contains a big change (Code of Conduct) to the repository.

Will it be good if I open a separate issue proposing the restructuring of the README and then get assigned?

This way, we will have a commit for each change.

**Comment by Sriparno08** [comment]
Hey @Aman1-coder, there is already a big change (Code of Conduct) included in this commit.

Will it be a good idea if I open a separate issue proposing the restructuring of the README and then get assigned to it.

This way, we will have a separate commit for each big change.

**Pull request merged**
